"""Software-only simulation on SYNTHETIC frames. No camera, no real data.

Scenarios: quiet scene, wind/vegetation flicker, a moving shadow (a false trigger
the classifier must reject), and an animal, a person and a vehicle crossing.
Writes dashboard/events.js so dashboard/index.html works by double-click.
"""
import json
import os
import sys
from datetime import datetime, timedelta

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from src.classifier import SimulatedClassifier  # noqa: E402
from src.pipeline import Pipeline  # noqa: E402

SIZE = 96
RNG = np.random.default_rng(7)
BASE = np.tile(np.linspace(90, 120, SIZE), (SIZE, 1))  # static background
SHAPES = {"animal": (20, 12), "human": (10, 24), "vehicle": (40, 18)}


def noisy(img, sigma=2.0):
    return np.clip(img + RNG.normal(0, sigma, img.shape), 0, 255)


def quiet(n):
    return [(noisy(BASE), "nothing") for _ in range(n)]


def wind(n):
    frames = []
    for _ in range(n):
        img = noisy(BASE, sigma=4.0)
        x = int(RNG.integers(10, 80))
        img[40:48, x:x + 8] += RNG.choice([-30, 30])  # small swaying branch
        frames.append((np.clip(img, 0, 255), "nothing"))
    return frames


def shadow(n):
    frames = []
    for i in range(n):
        img = BASE.copy()
        x = 6 * i
        img[:, max(0, x - 30):x] -= 45  # large soft shadow sweeping across
        frames.append((noisy(img), "nothing"))
    return frames


def crossing(kind, n=20):
    w, h = SHAPES[kind]
    frames = []
    for i in range(n):
        img = BASE.copy()
        x = 4 * i
        img[60 - h:60, x:x + w] = 220
        frames.append((noisy(img), kind))
    return frames


def build_stream():
    return (quiet(30) + wind(40) + quiet(20) + shadow(16) + quiet(15) + crossing("animal")
            + quiet(25) + crossing("human") + quiet(25) + crossing("vehicle") + quiet(30)
            + shadow(16) + quiet(20) + crossing("human"))


def main():
    stream = build_stream()
    pipe = Pipeline(SimulatedClassifier(seed=1))
    t = datetime(2026, 9, 19, 2, 0, 0)
    for frame, truth in stream:
        pipe.process(frame, t.strftime("%Y-%m-%d %H:%M:%S"), hint=truth)
        t += timedelta(seconds=5)

    s = pipe.stats
    s["classifier_call_pct"] = round(100 * s["classifier_calls"] / s["frames"], 1)
    print("SIMULATION on synthetic frames (not real-world results)")
    print(json.dumps(s, indent=2))

    out = os.path.join(os.path.dirname(__file__), "..", "dashboard", "events.js")
    with open(out, "w") as f:
        f.write("// SIMULATED DATA generated by sim/simulate.py\n")
        f.write("window.EVENTS = " + pipe.logger.to_json() + ";\n")
        f.write("window.STATS = " + json.dumps(s) + ";\n")
    print("wrote", os.path.abspath(out))


if __name__ == "__main__":
    main()
