// SIMULATED DATA generated by sim/simulate.py
window.EVENTS = [
  {
    "timestamp": "2026-09-19 02:02:45",
    "class": "nothing",
    "confidence": 0.94,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:02:50",
    "class": "nothing",
    "confidence": 0.79,
    "action": "discard",
    "changed_fraction": 0.0111
  },
  {
    "timestamp": "2026-09-19 02:02:55",
    "class": "nothing",
    "confidence": 0.84,
    "action": "discard",
    "changed_fraction": 0.0114
  },
  {
    "timestamp": "2026-09-19 02:03:10",
    "class": "nothing",
    "confidence": 0.93,
    "action": "discard",
    "changed_fraction": 0.0103
  },
  {
    "timestamp": "2026-09-19 02:03:20",
    "class": "animal",
    "confidence": 0.61,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:03:25",
    "class": "nothing",
    "confidence": 0.88,
    "action": "discard",
    "changed_fraction": 0.0105
  },
  {
    "timestamp": "2026-09-19 02:03:35",
    "class": "nothing",
    "confidence": 0.9,
    "action": "discard",
    "changed_fraction": 0.0113
  },
  {
    "timestamp": "2026-09-19 02:03:40",
    "class": "nothing",
    "confidence": 0.93,
    "action": "discard",
    "changed_fraction": 0.0107
  },
  {
    "timestamp": "2026-09-19 02:03:45",
    "class": "nothing",
    "confidence": 0.75,
    "action": "discard",
    "changed_fraction": 0.0119
  },
  {
    "timestamp": "2026-09-19 02:03:50",
    "class": "nothing",
    "confidence": 0.73,
    "action": "discard",
    "changed_fraction": 0.0118
  },
  {
    "timestamp": "2026-09-19 02:04:00",
    "class": "nothing",
    "confidence": 0.72,
    "action": "discard",
    "changed_fraction": 0.0115
  },
  {
    "timestamp": "2026-09-19 02:04:05",
    "class": "nothing",
    "confidence": 0.9,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:04:10",
    "class": "nothing",
    "confidence": 0.91,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:04:15",
    "class": "nothing",
    "confidence": 0.92,
    "action": "discard",
    "changed_fraction": 0.0118
  },
  {
    "timestamp": "2026-09-19 02:04:20",
    "class": "nothing",
    "confidence": 0.86,
    "action": "discard",
    "changed_fraction": 0.0111
  },
  {
    "timestamp": "2026-09-19 02:04:25",
    "class": "nothing",
    "confidence": 0.9,
    "action": "discard",
    "changed_fraction": 0.0107
  },
  {
    "timestamp": "2026-09-19 02:04:40",
    "class": "nothing",
    "confidence": 0.97,
    "action": "discard",
    "changed_fraction": 0.0112
  },
  {
    "timestamp": "2026-09-19 02:04:55",
    "class": "nothing",
    "confidence": 0.83,
    "action": "discard",
    "changed_fraction": 0.0109
  },
  {
    "timestamp": "2026-09-19 02:05:00",
    "class": "nothing",
    "confidence": 0.96,
    "action": "discard",
    "changed_fraction": 0.0112
  },
  {
    "timestamp": "2026-09-19 02:05:05",
    "class": "nothing",
    "confidence": 0.88,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:05:10",
    "class": "nothing",
    "confidence": 0.8,
    "action": "discard",
    "changed_fraction": 0.0118
  },
  {
    "timestamp": "2026-09-19 02:05:15",
    "class": "nothing",
    "confidence": 0.95,
    "action": "discard",
    "changed_fraction": 0.0114
  },
  {
    "timestamp": "2026-09-19 02:05:20",
    "class": "nothing",
    "confidence": 0.85,
    "action": "discard",
    "changed_fraction": 0.0116
  },
  {
    "timestamp": "2026-09-19 02:05:25",
    "class": "nothing",
    "confidence": 0.85,
    "action": "discard",
    "changed_fraction": 0.0113
  },
  {
    "timestamp": "2026-09-19 02:05:30",
    "class": "nothing",
    "confidence": 0.77,
    "action": "discard",
    "changed_fraction": 0.0105
  },
  {
    "timestamp": "2026-09-19 02:05:35",
    "class": "nothing",
    "confidence": 0.97,
    "action": "discard",
    "changed_fraction": 0.0107
  },
  {
    "timestamp": "2026-09-19 02:05:45",
    "class": "nothing",
    "confidence": 0.96,
    "action": "discard",
    "changed_fraction": 0.011
  },
  {
    "timestamp": "2026-09-19 02:07:35",
    "class": "nothing",
    "confidence": 0.94,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:07:40",
    "class": "nothing",
    "confidence": 0.91,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:07:45",
    "class": "nothing",
    "confidence": 0.89,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:07:50",
    "class": "nothing",
    "confidence": 0.95,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:07:55",
    "class": "nothing",
    "confidence": 0.91,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:08:00",
    "class": "animal",
    "confidence": 0.57,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:05",
    "class": "nothing",
    "confidence": 0.82,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:10",
    "class": "nothing",
    "confidence": 0.73,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:15",
    "class": "nothing",
    "confidence": 0.53,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:20",
    "class": "nothing",
    "confidence": 0.78,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:25",
    "class": "human",
    "confidence": 0.49,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:30",
    "class": "nothing",
    "confidence": 0.78,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:35",
    "class": "nothing",
    "confidence": 0.97,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:40",
    "class": "nothing",
    "confidence": 0.84,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:45",
    "class": "nothing",
    "confidence": 0.86,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:08:50",
    "class": "nothing",
    "confidence": 0.72,
    "action": "discard",
    "changed_fraction": 0.3125
  },
  {
    "timestamp": "2026-09-19 02:10:05",
    "class": "animal",
    "confidence": 0.93,
    "action": "alert",
    "changed_fraction": 0.026
  },
  {
    "timestamp": "2026-09-19 02:10:10",
    "class": "animal",
    "confidence": 0.91,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:15",
    "class": "animal",
    "confidence": 0.85,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:20",
    "class": "animal",
    "confidence": 0.83,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:25",
    "class": "vehicle",
    "confidence": 0.5,
    "action": "discard",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:30",
    "class": "animal",
    "confidence": 0.85,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:35",
    "class": "animal",
    "confidence": 0.81,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:40",
    "class": "animal",
    "confidence": 0.86,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:45",
    "class": "animal",
    "confidence": 0.88,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:50",
    "class": "animal",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:10:55",
    "class": "animal",
    "confidence": 0.77,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:00",
    "class": "animal",
    "confidence": 0.94,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:05",
    "class": "animal",
    "confidence": 0.93,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:10",
    "class": "animal",
    "confidence": 0.79,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:15",
    "class": "animal",
    "confidence": 0.9,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:20",
    "class": "animal",
    "confidence": 0.46,
    "action": "discard",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:25",
    "class": "animal",
    "confidence": 0.79,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:30",
    "class": "animal",
    "confidence": 0.93,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:35",
    "class": "animal",
    "confidence": 0.8,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:40",
    "class": "animal",
    "confidence": 0.79,
    "action": "alert",
    "changed_fraction": 0.0104
  },
  {
    "timestamp": "2026-09-19 02:11:45",
    "class": "nothing",
    "confidence": 0.89,
    "action": "discard",
    "changed_fraction": 0.026
  },
  {
    "timestamp": "2026-09-19 02:13:50",
    "class": "human",
    "confidence": 0.8,
    "action": "alert",
    "changed_fraction": 0.026
  },
  {
    "timestamp": "2026-09-19 02:13:55",
    "class": "human",
    "confidence": 0.85,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:00",
    "class": "human",
    "confidence": 0.8,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:05",
    "class": "human",
    "confidence": 0.93,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:10",
    "class": "human",
    "confidence": 0.79,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:15",
    "class": "human",
    "confidence": 0.97,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:20",
    "class": "human",
    "confidence": 0.83,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:25",
    "class": "human",
    "confidence": 0.78,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:30",
    "class": "human",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:35",
    "class": "human",
    "confidence": 0.84,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:40",
    "class": "human",
    "confidence": 0.83,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:45",
    "class": "human",
    "confidence": 0.97,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:50",
    "class": "human",
    "confidence": 0.9,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:14:55",
    "class": "human",
    "confidence": 0.86,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:00",
    "class": "vehicle",
    "confidence": 0.53,
    "action": "discard",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:05",
    "class": "human",
    "confidence": 0.91,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:10",
    "class": "human",
    "confidence": 0.78,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:15",
    "class": "animal",
    "confidence": 0.6,
    "action": "discard",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:20",
    "class": "human",
    "confidence": 0.96,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:25",
    "class": "human",
    "confidence": 0.83,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:15:30",
    "class": "nothing",
    "confidence": 0.72,
    "action": "discard",
    "changed_fraction": 0.026
  },
  {
    "timestamp": "2026-09-19 02:17:35",
    "class": "vehicle",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0781
  },
  {
    "timestamp": "2026-09-19 02:17:40",
    "class": "vehicle",
    "confidence": 0.97,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:17:45",
    "class": "vehicle",
    "confidence": 0.76,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:17:50",
    "class": "vehicle",
    "confidence": 0.97,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:17:55",
    "class": "vehicle",
    "confidence": 0.85,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:00",
    "class": "vehicle",
    "confidence": 0.81,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:05",
    "class": "vehicle",
    "confidence": 0.9,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:10",
    "class": "vehicle",
    "confidence": 0.77,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:15",
    "class": "vehicle",
    "confidence": 0.89,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:20",
    "class": "vehicle",
    "confidence": 0.85,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:25",
    "class": "vehicle",
    "confidence": 0.95,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:30",
    "class": "vehicle",
    "confidence": 0.72,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:35",
    "class": "vehicle",
    "confidence": 0.81,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:40",
    "class": "vehicle",
    "confidence": 0.92,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:18:45",
    "class": "vehicle",
    "confidence": 0.78,
    "action": "alert",
    "changed_fraction": 0.0156
  },
  {
    "timestamp": "2026-09-19 02:19:15",
    "class": "nothing",
    "confidence": 0.94,
    "action": "discard",
    "changed_fraction": 0.0391
  },
  {
    "timestamp": "2026-09-19 02:21:50",
    "class": "nothing",
    "confidence": 0.81,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:21:55",
    "class": "nothing",
    "confidence": 0.9,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:22:00",
    "class": "nothing",
    "confidence": 0.98,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:22:05",
    "class": "nothing",
    "confidence": 0.91,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:22:10",
    "class": "human",
    "confidence": 0.36,
    "action": "discard",
    "changed_fraction": 0.0625
  },
  {
    "timestamp": "2026-09-19 02:22:15",
    "class": "nothing",
    "confidence": 0.79,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:20",
    "class": "nothing",
    "confidence": 0.85,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:25",
    "class": "nothing",
    "confidence": 0.81,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:30",
    "class": "nothing",
    "confidence": 0.78,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:35",
    "class": "nothing",
    "confidence": 0.92,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:40",
    "class": "nothing",
    "confidence": 0.85,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:45",
    "class": "nothing",
    "confidence": 0.92,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:50",
    "class": "nothing",
    "confidence": 0.83,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:22:55",
    "class": "nothing",
    "confidence": 0.98,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:23:00",
    "class": "nothing",
    "confidence": 0.75,
    "action": "discard",
    "changed_fraction": 0.125
  },
  {
    "timestamp": "2026-09-19 02:23:05",
    "class": "nothing",
    "confidence": 0.87,
    "action": "discard",
    "changed_fraction": 0.3125
  },
  {
    "timestamp": "2026-09-19 02:24:45",
    "class": "human",
    "confidence": 0.74,
    "action": "alert",
    "changed_fraction": 0.026
  },
  {
    "timestamp": "2026-09-19 02:24:50",
    "class": "human",
    "confidence": 0.87,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:24:55",
    "class": "human",
    "confidence": 0.81,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:00",
    "class": "human",
    "confidence": 0.86,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:05",
    "class": "human",
    "confidence": 0.95,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:10",
    "class": "human",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:15",
    "class": "human",
    "confidence": 0.88,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:20",
    "class": "nothing",
    "confidence": 0.34,
    "action": "discard",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:25",
    "class": "human",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:30",
    "class": "human",
    "confidence": 0.98,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:35",
    "class": "human",
    "confidence": 0.75,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:40",
    "class": "human",
    "confidence": 0.78,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:45",
    "class": "human",
    "confidence": 0.75,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:50",
    "class": "human",
    "confidence": 0.82,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:25:55",
    "class": "human",
    "confidence": 0.96,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:26:00",
    "class": "human",
    "confidence": 0.79,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:26:05",
    "class": "human",
    "confidence": 0.75,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:26:10",
    "class": "human",
    "confidence": 0.73,
    "action": "alert",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:26:15",
    "class": "vehicle",
    "confidence": 0.55,
    "action": "discard",
    "changed_fraction": 0.0208
  },
  {
    "timestamp": "2026-09-19 02:26:20",
    "class": "human",
    "confidence": 0.82,
    "action": "alert",
    "changed_fraction": 0.0208
  }
];
window.STATS = {"frames": 317, "idle": 180, "classifier_calls": 137, "alerts": 69, "discarded": 68, "classifier_call_pct": 43.2};
